### ISSUE TITLE
labs_lecture02 - lab03_pytorch_tensor2 - utils.py

### ISSUE THREAD

**Issue by ldkong1205** [xbresson/CE7454_2020#1]
Hi professor, I encountered the following error when I was trying to conduct the exercises on my PC:

TypeError
'float' object cannot be interpreted as an integer
  File "/Users/dongdongdongdong/Desktop/utils.py", line 5, in <module>
    cmap = sns.diverging_palette(260, 10, sep=1, n=16, s=99, l=50, center="dark", as_cmap=True) # best

**Comment by xbresson** [comment]
Try to setup the python env with this
https://github.com/xbresson/CE7454_2020#local-installation-for-windows

**Comment by ldkong1205** [comment]
> Try to setup the python env with this
> https://github.com/xbresson/CE7454_2020#local-installation-for-windows

Ok. Thank you very much, Prof.  :)
